### PR TITLE
Fix JMX metric name for G1GC old generation statistics.

### LINKED ISSUE #230: Incorrect name for G1GC old generation JMX metric
The JMX metric name for collecting info on G1GC old generation counts and durations is incorrectly named. The default config file uses the name 'G1 Mixed Generation' when it should be 'G1 Old Generation'. I've confirmed this using visualvm on a running Java 8, 11 and 12 VM.

In the default config file (new-gc-default-jmx-metrics.yaml) the stanza at the bottom that reads

```yaml
- include:
    domain: java.lang
    type: GarbageCollector
    name: G1 Mixed Generation
    attribute:
      CollectionCount:
        alias: jvm.gc.major_collection_count
        metric_type: counter
      CollectionTime:
        alias: jvm.gc.major_collection_time
        metric_type: counter
```
should be
```yaml
- include:
    domain: java.lang
    type: GarbageCollector
    name: G1 Old Generation
    attribute:
      CollectionCount:
        alias: jvm.gc.major_collection_count
        metric_type: counter
      CollectionTime:
        alias: jvm.gc.major_collection_time
        metric_type: counter
```

### PR DESCRIPTION
**Pull request by dpratt**
Fixes #230

### CODE REVIEW

**Comment by albertvaka** [comment]
Hi @dpratt! Thanks for your PR 😃 

Can we be sure `G1 Mixed Generation` is not used in any JVM?

**Comment by dpratt** [comment]
@albertvaka I can't say for sure that it isn't, but across OpenJDK Java 8, 9, 10, 11 and 12 it's referenced as "G1 Old Generation".

I heavily suspect that if it were to show up it would likely be mutually exclusive with the name referenced above - it couldn't hurt to have both of them in the default JMX config file for safety purposes.

**Comment by albertvaka** [comment]
@dpratt can you change the PR to keep both the `Mixed` and `Old` names? It shouldn't hurt to have both, and it gives us the certainty that this is not a breaking change.

**Comment by dpratt** [comment]
Done - I've pushed that change.

**Comment by albertvaka** [comment]
Thanks a lot @dpratt, merging! 😄

**Pull request merged**
