### PR TITLE
Add tests for refresh_beans and refresh_beans_initial

### PR DESCRIPTION
**Pull request by ian28223**
Related to #349 

Adds tests for both `refresh_beans_initial` and `refresh_beans`

- AC-800

### CODE REVIEW

**Review by sgnn7 — DISMISSED** [review]
@ian28223 LGTM. I do feel like sleeping in unit tests is a bit of a problematic pattern but  I don't know if there's a better way to do this (without reworking the code heavily).

**Comment by ian28223** [comment]
> @ian28223 LGTM. I do feel like sleeping in unit tests is a bit of a problematic pattern but I don't know if there's a better way to do this (without reworking the code heavily).

I've reduced the sleep time to cut down on the overall runtime of the test. I hope this helps a bit

**Comment by sgnn7** [comment]
@ian28223 This LGTM but we should probably wait for @truthbk to maybe add some feedback if we can remove the `sleep`s entirely.

**Review by sgnn7 — APPROVED** [review]

**Review by truthbk — COMMENTED** [review]
The issue with the sleeps is not as much a problem with test duration (though it's always nice to keep these as short as possible), but rather with the fact it often turns out to be a bit of an  anti-pattern that introduces flaky tests.

It's unclear to me, with the current code, how we can avoid sleeping at all, so I think I'm fine with this.

**Pull request merged**
